'use strict';

(function () {
  const PLAYERS = [
    {
      id: 0,
      isBot: false,
      isActive: false,
      isFold: false,
      name: 'Бронепух',
      cash: 5000,
      rate: 0,
      isDiller: false,
      hand: [],
      combination: [],
      hightCard: [],
      kikker: [],
      couple: [],
      set: [],
      street: [],
      flush: [],
      fullhouse: [],
      kare: [],
      streetflush: [],
      royalflush: [],
      power: 0,
    },
    {
      id: 0,
      isBot: true,
      isActive: false,
      isFold: false,
      name: 'Люк Скайвокер',
      cash: 5000,
      rate: 0,
      isDiller: false,
      hand: [],
      combination: [],
      hightCard: [],
      kikker: [],
      couple: [],
      set: [],
      street: [],
      flush: [],
      fullhouse: [],
      kare: [],
      streetflush: [],
      royalflush: [],
      power: 0,
    },
    {
      id: 0,
      isBot: true,
      isActive: false,
      isFold: false,
      name: 'R2-D2',
      cash: 5000,
      rate: 0,
      isDiller: false,
      hand: [],
      combination: [],
      hightCard: [],
      kikker: [],
      couple: [],
      set: [],
      street: [],
      flush: [],
      fullhouse: [],
      kare: [],
      streetflush: [],
      royalflush: [],
      power: 0,
    },
    {
      id: 0,
      isBot: true,
      isActive: false,
      isFold: false,
      name: 'Лея',
      cash: 5000,
      rate: 0,
      isDiller: false,
      hand: [],
      combination: [],
      hightCard: [],
      kikker: [],
      couple: [],
      set: [],
      street: [],
      flush: [],
      fullhouse: [],
      kare: [],
      streetflush: [],
      royalflush: [],
      power: 0,
    },
    {
      id: 0,
      isBot: true,
      isActive: false,
      isFold: false,
      name: 'Йода',
      cash: 5000,
      rate: 0,
      isDiller: false,
      hand: [],
      combination: [],
      hightCard: [],
      kikker: [],
      couple: [],
      set: [],
      street: [],
      flush: [],
      fullhouse: [],
      kare: [],
      streetflush: [],
      royalflush: [],
      power: 0,
    },
    {
      id: 0,
      isBot: true,
      isActive: false,
      isFold: false,
      name: 'Дарт Вейдер',
      cash: 5000,
      rate: 0,
      isDiller: false,
      hand: [],
      combination: [],
      hightCard: [],
      kikker: [],
      couple: [],
      set: [],
      street: [],
      flush: [],
      fullhouse: [],
      kare: [],
      streetflush: [],
      royalflush: [],
      power: 0,
    },
  ];

  window.data = {
    players: PLAYERS,
  }
})();
